/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Amplang;


import Koneksi.dbKoneksi;
import com.mysql.cj.xdevapi.Statement;    
import java.sql.*;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class halamanBarang extends javax.swing.JInternalFrame {

    public Statement st;
    public ResultSet rs;
    Connection conn = Koneksi.dbKoneksi.getKoneksi();

    public halamanBarang() {
        initComponents();
        tampildata();
    }
    
    private void clear(){
        txtNama.setText("");
        txtBerat.setText("");
        txtID.setText("");
        txtStok.setText("");
        
        btnAdd.setText("Simpan");
        txtID.setEditable(true);
    }
    
    private void searching(){
    String search = "";

    int selectedIndex = cmbCari.getSelectedIndex();
    if (selectedIndex == 0) {
        search = "idBarang";
    } else if (selectedIndex == 1) {
        search = "namaBarang";
    }
        try{
            java.sql.Statement stat = (java.sql.Statement) dbKoneksi.getKoneksi().createStatement();
            rs = stat.executeQuery("SELECT * FROM tbbarang WHERE " + search + 
                                    " LIKE '%" + txtCari.getText() + "%'");

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No.");
            model.addColumn("ID");
            model.addColumn("Nama Barang");
            model.addColumn("Berat Barang");
            model.addColumn("Jenis Ikan");
            model.addColumn("Stok Barang");
            
            int no = 1 ;
            while (rs.next()) {
                Object[] data = {
                    no++,
                    rs.getString("idBarang"),
                    rs.getString("namaBarang"),
                    rs.getString("beratBarang"),
                    rs.getString("jenisIkan"),
                    rs.getString("stokBarang")
                };
                model.addRow(data);
            }
            tbDataBarang.setModel(model);

        }catch(Exception e){
            
        }
        
    }
    
    
    
    
    private void tampildata(){
        try{
            java.sql.Statement stat = (java.sql.Statement) dbKoneksi.getKoneksi().createStatement();
            rs = stat.executeQuery("SELECT * FROM tbbarang");

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No.");
            model.addColumn("ID");
            model.addColumn("Nama Barang");
            model.addColumn("Berat Barang");
            model.addColumn("Jenis Ikan");
            model.addColumn("Stok Barang");
            
            int no = 1 ;
            while (rs.next()) {
                Object[] data = {
                    no++,
                    rs.getString("idBarang"),
                    rs.getString("namaBarang"),
                    rs.getString("beratBarang"),
                    rs.getString("jenisIkan"),
                    rs.getString("stokBarang")
                };
                model.addRow(data);
            }
            tbDataBarang.setModel(model);

        }catch(Exception e){
            
        }
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbDataBarang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtBerat = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmbCari = new javax.swing.JComboBox<>();
        txtCari = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rbTenggiri = new javax.swing.JRadioButton();
        rbPipih = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        tbDataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Barang", "Berat", "Jenis Ikan", "Stok Barang"
            }
        ));
        tbDataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDataBarang);

        jLabel2.setText("Nama Barang");

        jLabel3.setText("Berat Barang");

        jLabel4.setText("ID Barang");

        jLabel5.setText("Stock Barang");

        jLabel6.setText("Jenis Ikan");

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel7.setText("SEARCHING");

        cmbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Barang", "Nama Barang" }));

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        jLabel8.setText("gr");

        rbTenggiri.setText("Tenggiri");

        rbPipih.setText("Pipih");

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA BARANG");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/headerbarang.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/headerbarang.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(jLabel9)
                .addGap(258, 258, 258))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(57, 57, 57))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(4, 4, 4)))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel8))
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(102, 102, 102)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(27, 27, 27)
                                            .addComponent(rbTenggiri)
                                            .addGap(35, 35, 35)
                                            .addComponent(rbPipih))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnAdd)
                                            .addGap(49, 49, 49)
                                            .addComponent(btnDelete))))
                                .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(rbTenggiri)
                    .addComponent(rbPipih))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    String Jenis;
    Jenis = "";
    if (rbPipih.isSelected()){
        Jenis = "Pipih";
    }
    else if (rbTenggiri.isSelected()) {
        Jenis = "Tenggiri";
    }
        
        
        try{
            java.sql.Statement stat=(java.sql.Statement)dbKoneksi.getKoneksi().createStatement();
             if(txtID.getText().equals("") || 
                     txtNama.getText().equals("") || 
                     txtBerat.getText().equals("") || 
                     txtStok.getText().equals("") ||Jenis.equals("")){
                JOptionPane.showMessageDialog(null, "DATA TIDAK BOLEH KOSONG");
                return;
            }
            // add data
            if(btnAdd.getText() == "ADD"){
                String cek = "SELECT * FROM tbbarang where idBarang = '" + txtID.getText() + "'";
                rs=stat.executeQuery(cek);
                if (rs.next()){
                    JOptionPane.showMessageDialog(null, "ID Ini Sudah Ada...");
                }else{
                    String sql = "INSERT INTO tbbarang VALUES('" + txtID.getText() + 
                            "','" + txtNama.getText().toUpperCase() + 
                            "','" + txtBerat.getText().toUpperCase() + 
                            "','" + txtStok.getText().toUpperCase() + 
                            "','" + Jenis.toUpperCase() + "')";
                    stat.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Berhasil Menambahkan Data..");
                    tampildata();
                    clear();
                }
            }
            // ubah data
            else{
                String update = "UPDATE tbbarang SET namaBarang = '" + txtNama.getText() + 
                            "', beratBarang = '" + txtBerat.getText() + 
                            "', stokBarang = '" + txtStok.getText() + 
                            "', jenisIkan = '" + Jenis + 
                            "' WHERE idBarang = '" + txtID.getText() + "')";
                    stat.executeUpdate(update);
                    JOptionPane.showMessageDialog(null, "Data berhasil diubah..");
                    tampildata();
                    clear();
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tbDataBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataBarangMouseClicked
        
        
        txtID.setText(tbDataBarang.getValueAt(tbDataBarang.getSelectedRow(), 1).toString());
        txtNama.setText(tbDataBarang.getValueAt(tbDataBarang.getSelectedRow(), 2).toString());
        txtBerat.setText(tbDataBarang.getValueAt(tbDataBarang.getSelectedRow(), 3).toString());
        String jenis = tbDataBarang.getValueAt(tbDataBarang.getSelectedRow(), 4).toString();
            if (jenis.equals("TENGGIRI")) {
                rbTenggiri.setSelected(true);
                rbPipih.setSelected(false);
            } else if (jenis.equals("PIPIH")) {
                rbTenggiri.setSelected(false);
                rbPipih.setSelected(true);
            }
        txtStok.setText(tbDataBarang.getValueAt(tbDataBarang.getSelectedRow(), 5).toString());
        
        txtID.setEditable(false);
        btnAdd.setText("Ubah");
    }//GEN-LAST:event_tbDataBarangMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(txtID.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Silakan Pilih Data Yang di Hapus");
        }else{
            int jawab = JOptionPane.showInternalConfirmDialog(null,"Data ini akan diHapus, Lanjutkan ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if(jawab==0){
                try{
                    java.sql.Statement stat=(java.sql.Statement)dbKoneksi.getKoneksi().createStatement();
                    String sql = "DELETE FROM tbbarang WHERE idBarang = '" + txtID.getText() + "'";
                    stat.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data Berhasil diHapus..");
                    tampildata();
                    clear();
                } catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        searching();
    }//GEN-LAST:event_txtCariKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> cmbCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbPipih;
    private javax.swing.JRadioButton rbTenggiri;
    private javax.swing.JTable tbDataBarang;
    private javax.swing.JTextField txtBerat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
